spring.application.name=blogger-box-backend

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://db.chbdyfvwmurawoccejep.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=XDM7CniIdi5IYdj9

spring.jpa.hibernate.ddl-auto=validate

